version: 0.0
os: linux
files:
  - source: /src
    destination: /var/www/php
hooks:
  ApplicationStop:
    - location: scripts/stop_apache.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install_dependencias.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root